version: '3'
services:
  cuidar-app:
    restart: always
    image: cuidar-app
    volumes:
      # Config Directory
      - ./config:/usr/src/app/config
      # Data Directory
      - ./data:/usr/src/app/data
      # Reports Directory
      - ./reports:/usr/src/app/reports
      # Script Directory
      - ./scripts:/usr/src/app/scripts
    env_file:
      - config/environment
      - config/secrets
    command: bash
